#!/usr/bin/env python3
"""Emit `logic` declarations for every port of rtl/msx.sv, so a bench can wire
the machine with `.*` instead of 172 hand-typed connections -- and so the bench
breaks loudly when a port is added, instead of silently leaving it floating.

    python3 sim/fullsys/mkports.py > sim/fullsys/gen/msx_ports.svh
"""
import re, sys

src = open("rtl/msx.sv").read()
body = re.search(r'module\s+msx\s*\((.*?)\n\);', src, re.S).group(1)

out, n = [], 0
for line in body.split('\n'):
    l = line.split('//')[0].strip().rstrip(',')
    if not l:
        continue
    m = re.match(r'(input|output)\s+(?:logic\s+|wire\s+|reg\s+)?(.*)$', l)
    if not m:
        continue
    rest = m.group(2).strip()
    first = rest.split()[0]
    #  A struct/enum type keeps its type; a range or a bare name becomes `logic`.
    if '::' in first or first.endswith('_t'):
        decl = rest
    else:
        decl = 'logic ' + rest
    out.append(f"   {decl};")
    n += 1

print(f"//  Generated by sim/fullsys/mkports.py from rtl/msx.sv -- {n} ports.")
print("//  Do not edit; re-run prep.sh.")
print('\n'.join(out))
